version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092

    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    depends_on:
      - zookeeper
    volumes:
      - ./data/kafka:/var/run/docker.sock  
  consumer:
    image: "myapp"
    build: ./KafkaConsumer
    container_name: consumer

    depends_on:
      - db
      - kafka
    expose:
      - "8081"
    #ports:
      #- "8081:8081"
    env_file:
      - .env
    environment:
      - BOOTSTRAP_SERVERS_CONFIG=${BOOTSTRAP_SERVERS_CONFIG}
      - MOVIE_TOPIC=${MOVIE_TOPIC}
      - REVIEW_TOPIC=${REVIEW_TOPIC}
      - UPVOTE_TOPIC=${UPVOTE_TOPIC}
      - URL_DB=${URL_DB}
      - USERNAME_DB=${USERNAME_DB}
      - PASSWORD_DB=${PASSWORD_DB}
  producer:
    image: "myapp2"
    build: ./KafkaProducer
    container_name: producer
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - BOOTSTRAP_SERVERS_CONFIG=${BOOTSTRAP_SERVERS_CONFIG}
      - MOVIE_TOPIC=${MOVIE_TOPIC}
      - REVIEW_TOPIC=${REVIEW_TOPIC}
      - UPVOTE_TOPIC=${UPVOTE_TOPIC}
  db:
    image: 'postgres:13.1-alpine'

    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${USERNAME_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - "5432"